import React from 'react'
import {BrowserRouter,  Routes, Route} from 'react-router-dom'
import ClientsPage from '../components/ClientsPage.jsx'
import LoginPage from '../components/LoginPage.jsx'
import ErrorPage from '../components/ErrorPage.jsx'

const Paths = () => {
  return (
    <BrowserRouter>
    <Routes >
    <Route path="/" element={<LoginPage></LoginPage>} ></Route>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "
    <Route path="/login" element={<LoginPage></LoginPage>} ></Route>   
    <Route path="/clients" element={<ClientsPage></ClientsPage>} ></Route>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   "
    <Route path="*" element={<ErrorPage></ErrorPage>} ></Route>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   "
    </Routes>
  </BrowserRouter>
  )
}

export default Paths